package com.nazaninfz.saga.orchestrator.core.enums;

public enum RemoteStatus {

    READY_TO_SEND,
    RECEIVE_RESPONSE,
    PARSED_RESPONSE,

    EMPTY_MESSAGING_DATA,
    PARSE_RESPONSE_FAILED,
    MESSAGING_LAYER_EXCEPTION,
    TIMEOUT,
    MICRO_SERVICE_THROWS_EXCEPTION,

    COMMIT_UNKNOWN_FAILED,

    ROLLBACK_HAS_NOT_STARTED,
    ROLLBACK_STARTED,
    ROLLBACK_SUCCESSFULLY,
}
